# Generated by Django 4.1.7 on 2023-03-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_locaction_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='locaction',
            new_name='location',
        ),
    ]
