# Generated by Django 4.1.7 on 2023-03-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_locaction_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_image',
            new_name='profile_image',
        ),
    ]
