# Generated by Django 4.1.7 on 2023-03-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created', 'title']},
        ),
    ]
